"""
Step 01 -- Automated Drift & Missing-Value Tracking

SDK mechanics demonstrated:
  1. `CometMPM(...)` -- one client per model, created once.
  2. `mpm.upload_dataset_csv(..., dataset_type="TRAINING_EVENTS")` -- makes a
     training distribution available to MPM as a *dataset object*.
  3. `mpm.log_event(...)` -- logs one production prediction, with the
     ground-truth label BUNDLED directly into the same call whenever it's
     already known (`labels=...`), instead of a separate call later.

All the data these calls send was already generated by
`00_generate_data/00_generate_data.py` -- this script's only job is to load
`data/training_baseline.csv` and `data/production_predictions.csv`, shape
each row into the exact payload each SDK call expects, and send it. There is
no data generation, model training, or scoring logic in this file.

--- Why `upload_dataset_csv(dataset_type="TRAINING_EVENTS")` isn't enough on
its own ---
This call uploads the CSV and registers it as a named dataset object under
the model -- that's it. It does NOT automatically become the model's active
drift baseline. You still have to go to the model's **Settings** tab in the
Comet UI and manually select this dataset as the baseline (a one-time step,
done once per model). Skip this and MPM silently falls back to comparing
each day's traffic to the *previous* day's traffic (period-over-period)
instead of to this stable baseline -- which, for a feature that freezes to a
constant, makes the drift metric actually drop toward zero right after the
break (every day looks identical to the day before it), the opposite of what
you want to see. This is the single most common thing people get wrong when
first wiring up MPM drift, so it's called out explicitly here and in
01_drift_and_missing_values.md.

--- Why labels are bundled into `log_event(...)`, not sent as a separate call
---
Comet MPM does support logging a label after the fact via a separate call,
merged into the matching prediction by `prediction_id` on a backend batch
job. In practice that job's timing isn't fast enough to rely on for a demo
(labels can sit unmerged for a day or more). Passing `labels={...}` directly
in the SAME `log_event(...)` call that logs the prediction guarantees the
label is attached the instant the event lands -- no merge job, no delay. The
tradeoff: you can only do this when the label is already known at logging
time. Here, each historical event's label is bundled only once
`config.LABEL_DELAY_DAYS` has "passed" relative to when the prediction was
made (computed once, in Step 00, as each row's `label_timestamp`) -- exactly
mirroring how a real batch backfill would only attach labels once ground
truth has actually arrived.

Docs: https://www.comet.com/docs/v2/guides/model-production-monitoring/send-mpm-data/

Usage:
    python 01_drift_and_missing_values/01_drift_and_missing_values.py --dry-run
    python 01_drift_and_missing_values/01_drift_and_missing_values.py
    python 01_drift_and_missing_values/01_drift_and_missing_values.py --limit 100
"""
import argparse
import os
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import pandas as pd
from dotenv import load_dotenv

import config

load_dotenv()


def load_production_predictions() -> pd.DataFrame:
    if not config.PRODUCTION_PREDICTIONS_CSV.exists() or not config.TRAINING_BASELINE_CSV.exists():
        raise SystemExit(
            "Missing data/production_predictions.csv or data/training_baseline.csv -- "
            "run 00_generate_data/00_generate_data.py first."
        )
    return pd.read_csv(config.PRODUCTION_PREDICTIONS_CSV)


def build_timeline(df: pd.DataFrame) -> list:
    """Shapes each row into an internal event dict. Most of these keys are
    passed straight through to `mpm.log_event(...)`; `model_version` is the
    exception -- it's NOT a `log_event()` parameter (confirmed against the
    installed SDK's signature). It's fixed per `CometMPM` client instead, so
    this script creates one client per version and uses this key only to
    pick which client logs the event (see run_live below).

        {
            "prediction_id":   str,          # your own unique ID -- used later
                                              # to correlate a label with its
                                              # prediction if you ever DO log
                                              # them separately
            "model_version":   str,          # picks which CometMPM client logs
                                              # this event -- lets you filter
                                              # the MPM UI (and correlate
                                              # against the Model Registry --
                                              # see Step 04) by deployment
            "input_features":  {name: value},  # becomes `feature_<name>` columns
            "output_features": {name: value},  # becomes `prediction_<name>` columns
            "labels":          {name: value} | None,  # becomes `label_value_<name>`
                                                        # columns once merged --
                                                        # omitted entirely (not
                                                        # sent as null) when not
                                                        # yet known
            "timestamp":       float,        # unix seconds -- lets you backfill
                                              # historical events instead of
                                              # only logging "now"
        }

    Note `input_features` only includes `lead_time_days` when the value is
    present -- an event simply omitting a feature key is how MPM's missing-
    value tracking is fed (there's no separate "mark this as missing" call).
    """
    events = []
    for row in df.itertuples(index=False):
        input_features = {
            "region": row.region,
            "product_category": row.product_category,
            "promo_flag": int(row.promo_flag),
            "season_index": float(row.season_index),
            "price_index": float(row.price_index),
            "days_since_last_shipment": float(row.days_since_last_shipment),
            "warehouse_inventory_level": float(row.warehouse_inventory_level),
        }
        if pd.notna(row.lead_time_days):
            input_features["lead_time_days"] = float(row.lead_time_days)

        event = {
            "timestamp": float(row.timestamp),
            "prediction_id": row.event_id,
            "model_version": row.model_version,
            "input_features": input_features,
            "output_features": {"predicted_units": float(row.predicted_units)},
        }
        # Bundle the label in only when it would realistically be known by
        # now (see module docstring) -- this is the whole reason
        # `label_timestamp` was precomputed back in Step 00.
        if row.label_timestamp <= time.time():
            event["labels"] = {"actual_units": float(row.demand_units)}
        events.append(event)

    events.sort(key=lambda e: e["timestamp"])
    return events


def run_dry_run(timeline: list) -> None:
    print("\n[dry-run] nothing was sent to Comet MPM\n")

    example = next(e for e in timeline if "labels" in e)
    print("Example event payload that WILL include a bundled label (log_event(**this)):")
    print(f"  {example}\n")

    example_no_label = next((e for e in timeline if "labels" not in e), None)
    if example_no_label:
        print("Example event payload for a too-recent prediction (no 'labels' key at all,")
        print("not a null/None value -- MPM treats a missing key as \"no label yet\", not as 0):")
        print(f"  {example_no_label}\n")

    n_with_label = sum(1 for e in timeline if "labels" in e)
    n_missing_lead_time = sum(1 for e in timeline if "lead_time_days" not in e["input_features"])
    n_before = sum(1 for e in timeline if e["model_version"] == config.MPM_MODEL_VERSION_BEFORE)
    n_after = sum(1 for e in timeline if e["model_version"] == config.MPM_MODEL_VERSION_AFTER)

    print(f"  training baseline rows to upload   : {len(pd.read_csv(config.TRAINING_BASELINE_CSV))}")
    print(f"  total production events to log      : {len(timeline)}")
    print(f"  events with a bundled 'labels' key  : {n_with_label}")
    print(f"  events with no 'labels' key (yet)   : {len(timeline) - n_with_label}")
    print(f"  events with no 'lead_time_days' key : {n_missing_lead_time} (this is how a missing")
    print("                                          value is represented -- an omitted key)")
    print(f"  events tagged model_version={config.MPM_MODEL_VERSION_BEFORE:<8}: {n_before}")
    print(f"  events tagged model_version={config.MPM_MODEL_VERSION_AFTER:<8}: {n_after}")


def run_live(timeline: list, limit: int = None) -> None:
    from comet_mpm import CometMPM

    api_key = os.getenv("COMET_API_KEY")
    workspace_name = os.getenv("COMET_WORKSPACE")

    # `model_version` is fixed per CometMPM CLIENT, not passed per-event to
    # log_event() (there is no such parameter -- confirmed against the
    # installed SDK's signature). Since this demo tags events with two
    # different versions (before/after the retrain), that means one client
    # per version, both pointed at the same model_name so they show up as
    # one model in MPM, filterable by version.
    mpm_before = CometMPM(
        api_key=api_key,
        workspace_name=workspace_name,
        model_name=config.MPM_MODEL_NAME,
        model_version=config.MPM_MODEL_VERSION_BEFORE,
    )
    mpm_after = CometMPM(
        api_key=api_key,
        workspace_name=workspace_name,
        model_name=config.MPM_MODEL_NAME,
        model_version=config.MPM_MODEL_VERSION_AFTER,
    )
    clients_by_version = {
        config.MPM_MODEL_VERSION_BEFORE: mpm_before,
        config.MPM_MODEL_VERSION_AFTER: mpm_after,
    }

    print(f"Uploading training baseline as dataset '{config.MPM_TRAINING_DATASET_NAME}'...")
    # dataset_type="TRAINING_EVENTS" is what tells MPM this CSV represents a
    # clean reference distribution (as opposed to e.g. "PREDICTION_EVENTS").
    # This call only REGISTERS the dataset -- it does not select it as the
    # active drift baseline. See the module docstring's "Why upload_dataset_csv
    # isn't enough on its own" section: that's still a manual Settings step.
    # The baseline applies to the model as a whole (drift-baseline selection
    # in Settings is a per-model setting, not per-version), so it only needs
    # uploading once -- via either client, arbitrarily the "before" one here.
    mpm_before.upload_dataset_csv(
        file_path=str(config.TRAINING_BASELINE_CSV),
        dataset_type="TRAINING_EVENTS",
        dataset_name=config.MPM_TRAINING_DATASET_NAME,
    )
    print("  done -- this dataset now exists under the model, but is NOT yet the drift baseline.")
    print("  Go set it manually: model > Settings > select this dataset as the baseline")
    print("  (see 01_drift_and_missing_values.md).")

    events_to_send = timeline[:limit] if limit else timeline
    print(f"\nLogging {len(events_to_send)} events to model '{config.MPM_MODEL_NAME}'...")
    from tqdm import tqdm
    for event in tqdm(events_to_send):
        # One call per prediction, routed to the client whose fixed
        # model_version matches this event's tag. `labels=event.get("labels")`
        # passes None (not an empty dict) for events too recent to have
        # ground truth -- the SDK omits the key entirely rather than sending
        # a null value. `timestamp=` backdates the event to when the
        # prediction actually happened in the simulation, rather than
        # logging everything as "now".
        clients_by_version[event["model_version"]].log_event(
            prediction_id=event["prediction_id"],
            input_features=event["input_features"],
            output_features=event["output_features"],
            labels=event.get("labels"),
            timestamp=event["timestamp"],
        )

    print("\nFlushing remaining events to Comet (this can take a minute)...")
    # log_event() batches under the hood -- end() blocks until every
    # buffered event has actually been sent (or failed) before returning.
    # Both clients need flushing, since events were split across them.
    mpm_before.end()
    mpm_after.end()

    errors = []
    for mpm in (mpm_before, mpm_after):
        if mpm.has_logging_error():
            errors.extend(mpm.get_logging_errors())
    if errors:
        for err in errors[:10]:
            print(f"  - {err['message']}")
    else:
        print("All events sent successfully.")
    print(f"\nOpen the MPM model page in Comet: workspace='{workspace_name}', model='{config.MPM_MODEL_NAME}'.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="Validate locally, send nothing to Comet.")
    parser.add_argument("--limit", type=int, default=None, help="Only send the first N prediction events.")
    args = parser.parse_args()

    scored = load_production_predictions()
    timeline = build_timeline(scored)

    no_creds = not (os.getenv("COMET_API_KEY") and os.getenv("COMET_WORKSPACE"))
    if args.dry_run or no_creds:
        if no_creds and not args.dry_run:
            print("No COMET_API_KEY/COMET_WORKSPACE set -- falling back to --dry-run.")
        run_dry_run(timeline)
        print("\nNext: fill in .env, then re-run without --dry-run to send data to Comet MPM.")
    else:
        run_live(timeline, limit=args.limit)
        print("\nSee 01_drift_and_missing_values.md for the UI checklist.")


if __name__ == "__main__":
    main()
